/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_vincent_android_study_2020_ndk_Hello */

#ifndef _Included_com_vincent_android_study_2020_ndk_Hello
#define _Included_com_vincent_android_study_2020_ndk_Hello
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_vincent_android_study_2020_ndk_Hello
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_vincent_android_1study_12020_ndk_Hello_sayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
